# Generated by Django 4.0.4 on 2022-05-16 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id_recipe', models.BigAutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('recipe_name', models.CharField(max_length=120)),
                ('recipe_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nesti2_recipe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.BigAutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'nesti2_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id_city', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'nesti2_city',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id_image', models.BigAutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('i_name', models.CharField(max_length=250)),
                ('extension', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'nesti2_image',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='test', max_length=128)),
            ],
            options={
                'db_table': 'nesti2_product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.BigAutoField(primary_key=True, serialize=False)),
                ('adress_1', models.CharField(max_length=50)),
                ('adress_2', models.CharField(blank=True, max_length=50, null=True)),
                ('creations_date', models.DateTimeField(blank=True, null=True)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=1)),
                ('id_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.city')),
            ],
            options={
                'db_table': 'nesti2_user',
                'managed': True,
            },
        ),
    ]
